apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    isDefault: true
    access: proxy
    uid: CbuXHY8Iz
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
