services:
  backend:
    image: ghcr.io/koutsoulis/cryptofeedaggregator-backend:latest
    container_name: cryptofeedaggregator-backend
    restart: unless-stopped
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "4041:4041"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: cryptofeedaggregator-prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:11.2.2
    container_name: cryptofeedaggregator-grafana
    restart: unless-stopped
    environment:
      GF_SERVER_DOMAIN: metrics.koutsoulis.work
      GF_SERVER_ROOT_URL: https://metrics.koutsoulis.work
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./grafana/dashboard_config.yaml:/etc/grafana/provisioning/dashboards/dashboard_config.yaml:ro
      - ./grafana/dashboard.json:/etc/grafana/dashboards/dashboard.json:ro
    ports:
      - "3002:3000"
    depends_on:
      - prometheus

volumes:
  grafana_data:
  prometheus_data:
